# -*- coding: utf-8 -*-
"""Pract_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQgcWESE4v9sJl_9gDkRs__kpjm2xJG9
"""

# Задача 1

import numpy as np

def multiply_matrices(A, B, C):
    # Умножение матрицы A на B вручную
    result_AB = [[sum(a * b for a, b in zip(A_row, B_col)) for B_col in zip(*B)] for A_row in A]

    # Умножение результата на C вручную
    result_ABC = [[sum(ab * c for ab, c in zip(AB_row, C_col)) for C_col in zip(*C)] for AB_row in result_AB]

    return result_ABC

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
C = np.random.randint(1, 10, (3, 3))

result = multiply_matrices(A.tolist(), B.tolist(), C.tolist())
print(result)

# Задача 2

def generate_spiral_matrix(N):
    matrix = [[0] * N for _ in range(N)]
    num = 1
    left, right, top, bottom = 0, N - 1, 0, N - 1

    while left <= right and top <= bottom:
        for i in range(left, right + 1):
            matrix[top][i] = num
            num += 1
        top += 1

        for i in range(top, bottom + 1):
            matrix[i][right] = num
            num += 1
        right -= 1

        for i in range(right, left - 1, -1):
            matrix[bottom][i] = num
            num += 1
        bottom -= 1

        for i in range(bottom, top - 1, -1):
            matrix[i][left] = num
            num += 1
        left += 1

    return matrix

# Размер матрицы
N = int(input("Введите размер матрицы NxN: "))
spiral_matrix = generate_spiral_matrix(N)
for row in spiral_matrix:
    print(row)

# Задача 3

import numpy as np

# Определение будних дней (0 - понедельник, 4 - пятница)
weekdays = np.is_busday(np.arange('2015-02', '2015-03', dtype='datetime64[D]'))

num_weekdays = np.sum(weekdays)

print(f"Количество будних дней в феврале 2015 года: {num_weekdays}")

# Задача 4

import matplotlib.pyplot as plt
import numpy as np

data = np.random.randn(1000)

plt.hist(data, bins=30, edgecolor='pink', histtype='bar', hatch='/', color = 'purple')
plt.title("Гистограмма с текстурой")
plt.xlabel("Значения")
plt.ylabel("Частота")
plt.show()

# Задача 5

import numpy as np
import matplotlib.pyplot as plt

# Генерация случайных данных
x = np.random.randn(100)
y = np.random.randn(100)
sizes = np.random.rand(100) * 1000  # Разные размеры шариков

# Построение точечной диаграммы
plt.scatter(x, y, s=sizes, alpha=0.5, color = 'purple')
plt.title("Точечная диаграмма с шариками разного размера")
plt.xlabel("Ось X")
plt.ylabel("Ось Y")
plt.show()